import * as XLSX from "xlsx";

type ExportOptions = {
  title: string;

  company?: string;

  generatedBy?: string;

  generatedAt?: Date;

  filters?: Record<string, string>;

  sheetName: string;

  fileName: string;

  rows: Record<string, any>[];
};

export function exportExcel({
  title,
  company = "ZICO BUSINESS ERP",
  generatedBy,
  generatedAt = new Date(),
  filters = {},
  sheetName,
  fileName,
  rows,
}: ExportOptions) {
  const data: any[][] = [];

  /* =========================
     COMPANY
  ========================= */

  data.push([company]);

  /* =========================
     REPORT TITLE
  ========================= */

  data.push([title]);

  data.push([]);

  /* =========================
     GENERATED INFO
  ========================= */

  data.push([
    "Generated",
    generatedAt.toLocaleString("en-GB"),
  ]);

  if (generatedBy) {
    data.push([
      "Generated By",
      generatedBy,
    ]);
  }

  /* =========================
     FILTERS
  ========================= */

  const filterEntries =
    Object.entries(filters).filter(
      ([, value]) =>
        value !== undefined &&
        value !== null &&
        value !== "",
    );

  if (filterEntries.length > 0) {
    data.push([]);

    data.push(["Filters"]);

    filterEntries.forEach(([key, value]) => {
      data.push([key, value]);
    });
  }

  data.push([]);

  /* =========================
     TABLE
  ========================= */

  const worksheet =
    XLSX.utils.aoa_to_sheet(data);

  XLSX.utils.sheet_add_json(
    worksheet,
    rows,
    {
      origin: data.length,
      skipHeader: false,
    },
  );

  /* =========================
     COLUMN WIDTH
  ========================= */

  if (rows.length > 0) {
    worksheet["!cols"] = Object.keys(
      rows[0],
    ).map((key) => ({
      wch: Math.max(
        key.length + 4,
        18,
      ),
    }));
  }

  /* =========================
     WORKBOOK
  ========================= */

  const workbook =
    XLSX.utils.book_new();

  XLSX.utils.book_append_sheet(
    workbook,
    worksheet,
    sheetName,
  );

  XLSX.writeFile(
    workbook,
    fileName,
  );
}